name: My GitHub Actions Pipeline

on:
  push:
    branches: [ main ]  # Зміни main на master, якщо твій репозиторій використовує master
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build code
        run: echo "Building project..."

